spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      server:
        webflux:
          discovery:
            locator:
              enabled: true
              lower-case-service-id: true
          routes:
            - id: auth-service
              uri: lb://auth-service
              predicates:
                - Path=/auth/**
            - id: user-service
              uri: lb://user-service
              predicates:
                - Path=/user/**
            - id: order-service-order
              uri: lb://order-service
              predicates:
                - Path=/order/**
            - id: order-service-item
              uri: lb://order-service
              predicates:
                - Path=/items/**
server:
  port: 8090

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka/